# Generated by Django 4.0.4 on 2022-04-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbID', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('genres', models.CharField(max_length=200)),
                ('isAdult', models.BooleanField()),
                ('runTimeMinutes', models.IntegerField()),
                ('releaseYear', models.CharField(max_length=50)),
                ('numVotes', models.IntegerField()),
            ],
        ),
    ]
